openapi: 3.1.0
info:
  title: RuntimeJoin Planning Contract
  version: 1.0.0
  description: >-
    Planning-time API contract for validating, resolving, and previewing
    RuntimeJoin definitions used by update operations.
servers:
  - url: https://example.invalid
paths:
  /v1/runtime-joins/validate:
    post:
      summary: Validate RuntimeJoin definitions
      operationId: validateRuntimeJoins
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RuntimeJoinValidationRequest'
      responses:
        '200':
          description: Validation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RuntimeJoinValidationResult'
  /v1/runtime-joins/resolve:
    post:
      summary: Resolve RuntimeJoin datasets and resolver selection
      operationId: resolveRuntimeJoins
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RuntimeJoinResolveRequest'
      responses:
        '200':
          description: Resolution result with concrete dataset versions and resolver choices
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RuntimeJoinResolveResult'
  /v1/runtime-joins/execute-preview:
    post:
      summary: Preview RuntimeJoin execution metadata
      operationId: previewRuntimeJoinExecution
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RuntimeJoinPreviewRequest'
      responses:
        '200':
          description: Preview of join execution plan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RuntimeJoinPreviewResult'
components:
  schemas:
    RuntimeJoin:
      type: object
      required: [alias, dataset_id, on]
      properties:
        alias:
          type: string
          pattern: '^[a-zA-Z_][a-zA-Z0-9_]*$'
          minLength: 1
          maxLength: 64
        dataset_id:
          type: string
          format: uuid
        dataset_version:
          type: integer
          minimum: 1
        on:
          type: string
          minLength: 1
      additionalProperties: false
    Assignment:
      type: object
      required: [column, expression]
      properties:
        column:
          type: string
          minLength: 1
        expression:
          type: string
          minLength: 1
      additionalProperties: false
    UpdateArguments:
      type: object
      required: [assignments]
      properties:
        joins:
          type: array
          default: []
          items:
            $ref: '#/components/schemas/RuntimeJoin'
        assignments:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/Assignment'
      additionalProperties: false
    RuntimeJoinValidationRequest:
      type: object
      required: [operation_id, joins]
      properties:
        operation_id:
          type: string
        joins:
          type: array
          items:
            $ref: '#/components/schemas/RuntimeJoin'
        working_table:
          type: string
    RuntimeJoinValidationResult:
      type: object
      required: [operation_id, passed, checks]
      properties:
        operation_id:
          type: string
        passed:
          type: boolean
        checks:
          type: array
          items:
            $ref: '#/components/schemas/ValidationCheck'
    ValidationCheck:
      type: object
      required: [rule_id, status]
      properties:
        rule_id:
          type: string
          enum: [VAL-001, VAL-002, VAL-003, VAL-004, VAL-005, VAL-101, VAL-102, REF-001, REF-002, REF-003, REF-004, REF-005]
        status:
          type: string
          enum: [pass, fail]
        detail:
          type: string
    RuntimeJoinResolveRequest:
      type: object
      required: [project_id, period_id, joins]
      properties:
        project_id:
          type: string
          format: uuid
        period_id:
          type: string
        joins:
          type: array
          items:
            $ref: '#/components/schemas/RuntimeJoin'
    RuntimeJoinResolveResult:
      type: object
      required: [project_id, period_id, resolved]
      properties:
        project_id:
          type: string
          format: uuid
        period_id:
          type: string
        resolved:
          type: array
          items:
            $ref: '#/components/schemas/ResolvedRuntimeJoin'
    ResolvedRuntimeJoin:
      type: object
      required: [alias, dataset_id, resolved_dataset_version, resolver_source, temporal_mode]
      properties:
        alias:
          type: string
        dataset_id:
          type: string
          format: uuid
        resolved_dataset_version:
          type: integer
          minimum: 1
        resolver_source:
          type: string
          enum: [project_override, dataset_resolver, system_default]
        temporal_mode:
          type: string
          enum: [period, bitemporal]
    RuntimeJoinPreviewRequest:
      type: object
      required: [run_id, period_start_date, update_arguments]
      properties:
        run_id:
          type: string
          format: uuid
        period_start_date:
          type: string
          format: date
        update_arguments:
          $ref: '#/components/schemas/UpdateArguments'
    RuntimeJoinPreviewResult:
      type: object
      required: [run_id, join_plan]
      properties:
        run_id:
          type: string
          format: uuid
        join_plan:
          type: array
          items:
            $ref: '#/components/schemas/JoinPlanItem'
    JoinPlanItem:
      type: object
      required: [alias, join_type, period_filter]
      properties:
        alias:
          type: string
        join_type:
          type: string
          enum: [left]
        period_filter:
          type: string
          description: Applied temporal predicate expression for this join
